### ISSUE TITLE
Dump and Load Sysex

### ISSUE THREAD

**Issue by suburbanimal** [gligli/p600fw#102]
I used Snoize's Sysex Librarian to dump my patches and load them in another P600.
Both have a Teensy with 2.0 stable version.

The sysex dumps from both synths are 131 bytes which is odd knowing that could be hold the content of a single presets data.
In order to receive the data I put the P600 receive channel on Omni.

Have I missed something or this dump functionality isn't working?

In case that helps, here's the Hexadecimal data contained in the sysex file from the dump
F0006116 01002516 61020003 002F0000 7240070E 40170073 097F7F00 33094004 000F0100 37000303 0068003D 08007300 03020044 00000200 03400304 40770000 01000070 46007F7F 00000101 01000100 00000000 00010000 00000201 00010000 01000500 01010200 00007F7F 00020070 037F0A7F 00000000 7F7F7F7F 0F7F0000 0001F7

Merci ;)
Vincent

**Comment by hotswank** [comment]
Have you solved this issue and how?
