### ISSUE TITLE
At power up, always starts in MIDI sync

### ISSUE THREAD

**Issue by polluxsynth** [gligli/p600fw#49]
When powered up, the machine is always set to MIDI sync, regardless of what the previous setting was. Suggestion: save the sync setting so that when powering up it is the same as before.

**Comment by gligli** [comment]
I really do'nt know what could cause this, is it still an issue?

**Comment by polluxsynth** [comment]
Tested it again with the latest firmware built from the master branch, and it seems to work now. So don't know if it actually was an issue once, or I was mistaken. At any rate, it works now, so I'll close this one.
