### ISSUE TITLE
Confusing behavior of arpeggio pedal latch function

### ISSUE THREAD

**Issue by polluxsynth** [gligli/p600fw#58]
When in arpeggio mode:

Press notes, then press pedal, then release notes => notes latched, as expected
Release pedal => arpeggio stops, as expected.

However, when pressing the pedal first before the notes causes confusing behavior as follows:

Press pedal, then press notes, release notes => notes latched, as expected.
But then, release pedal => notes still latched (WRONG)
In this state, pressing extra notes causes them to be arpeggiated as well as long as they are held. 
Pressing pedal again, then press new notes => arpeggiates over these as well, as expected,
release notes => all notes continue to arpeggiate, as expected.
Now, releasing pedal => new notes are arpeggiated, but not the original ones. There's a certain logic to this, but it seems too convoluted to be useful.

I'm wondering if the ordinary sustain pedal function of the pedal is getting confused with the latch function in some way?

**Comment by gligli** [comment]
I remember wanting to do something clever, anyway better keep it simple...
