### ISSUE TITLE
Possible Race conditions

### ISSUE THREAD

**Issue by mink99** [gligli/p600fw#63]
Hi,
When the p600 is run from an external sequencer and receives midi clock / mmc (the internal sequencer is not running,) the midi stop command causes the p600 to switch from preset to parameter mode.

**Comment by mink99** [comment]
This does not always happen... The condition when I could not reproduce ...

**Comment by gligli** [comment]
MIDI bank select (CC#0) is used to change from preset mode to manual mode.
I suppose this was a glitch from the MIDI source, if you can reproduce it, feel free to reopen the issue.
