### ISSUE TITLE
First note played after power on for each voice may emit a 'thump'.

### ISSUE THREAD

**Issue by polluxsynth** [gligli/p600fw#68]
Some 3372 chips it seems have a larger CV feedthrough on the filter CV input than others. In the particular machine I have here one of the voices emits a fairly loud thump the first time it is triggered after power on. Looking at the input to the filter CV buffer the CV jumps rather far when the voice is triggered the first time, from 0V to a couple of volts. The voltage difference with max envelope is less tha this, for instance.

**Comment by snickell** [comment]
I get this issue too.
