### ISSUE TITLE
Strange MIDI CC behavior

### ISSUE THREAD

**Issue by hotswank** [gligli/p600fw#75]
If you manually change a parameter on the P600, it's MIDI CC stops working properly. If you reload the patch, all MIDI CCs work fine again.

BTW how does the coarse / fine MIDI CC work? Does it behave like NRPNs with CC 6 or do you have to split the 16383 fader into MSB and LSB bit? Or is course just 'fine' (pun intended)?

**Comment by gligli** [comment]
The last tweaked pot will always conflict with the MIDI CC setting, ie if youi tweak the cutoff on the P600, CC cutoff will not work properly. Just move another pot or yeah, reload the patch, and it will work again.

Parameter values are editable on 14bits, coarse are the upper 7, and fine are the lower 7, so yeah just the coarse one can be enough.
