### ISSUE TITLE
P600 preset mode

### ISSUE THREAD

**Issue by ernstfliek** [gligli/p600fw#85]
Hi,

Installed the teensy and all seems fine but the preset mode.
In preset mode, whatever preset I choose, say 98, preset 00 shows up.
What could be the problem.

Best regards,

Ernst.

**Comment by gligli** [comment]
Hello,

That is because there are no presets stored in the 100 locations.
Just save a patch to any number and then you will ba able to recall it.
Alternatively, you could load the Z80 Presets sysex to have something in all the 100 locations

**Comment by ernstfliek** [comment]
Hi,

Thanks, my mistake.
