### ISSUE TITLE
Nothing at all happening?

### ISSUE THREAD

**Issue by bradholland** [gligli/p600fw#88]
Hi there, 
I'm a reasonably experienced tech. And have followed instructions to the letter.
The teensy programs just fine, and I have tried two different teensies.
The synth works just fine on the original Z80 but appears dead when the teensie is installed. 
The power supply has been recapped. 

When I turn the synth on with the teensie installed, its led lights up for about 1-2 seconds then goes off. 
Having cut the 5v trace on the teensie and removed the battery, I can program the teensie in situ seems to program fine, but still nothing...

Does this sound like any familiar issue?

thanks in advance for any responses.

**Comment by bradholland** [comment]
I should point out, that when I mean dead, the control panel doesnt light up or do anything.

**Comment by bradholland** [comment]
moral of the story is, don't by chinese clone teensies...

**Comment by gligli** [comment]
Ah yeah true, teensy clones, eg. from EBay don't work with p600fw...

**Comment by bradholland** [comment]
it may be that they have an arduino bootloader?

**Comment by bradholland** [comment]
in any case, works just great with an original.

**Comment by gligli** [comment]
Probably, I use part of the teensy bootloader to save stuff to flash.
